NUEntity.js
NUService.js

Support for associated entities.

---

NUAttribute.js
NUEntity.js

- setting attribute value as null in case value is null

handle integer object

---

NUAttribute.js

the `==` takes care of both null and undefined

fix mandatory attr validation

---

NURESTUser.js

needed for permissions implementation

added isOperator()

---

NURESTUser.js

UserRole.js already has hasAdminOperator() and hasSystem() implemented

adimOperator util method

---

elasticsearch/ESService.test.js

@natabal 
Fix test case for scroll data.

fix test case for scroll

---

VSDService.js
elasticsearch/ESService.js

@natabal 
Handling error and fix the issue to generate request id to save data in the store.
Please have a look.

handle error and fix request id issue

---

VSDService.js

@natabal 
Put the check for an empty array.

Initialize search with empty array

---

VSDService.js
tabify/alarmCountTabify.js
tabify/index.js

@natabal Added the Custom Tabify feature. Please review.

Add tabify service

---

NURESTConnection.js

Will be used by caller, for example health monitor, to determine nature of error

Include responseStatusCode in response object

---

NURESTConnection.js

Reverts nuagenetworks/js-bambou#66

Revert "Include responseStatusCode in response object"

---

elasticsearch/ESTabify.js

Added missing library in ESTabify

Add library

---

elasticsearch/ESRESTConnection.js

Replace api version for ES

---

NURESTConnection.js
NUService.js

- adding status codes similar to cappuccino
- removing the re-login login

Add status code error messages to be on par with previous system

---

NUService.js

Shall be used to remove 'X-Nuage-ProxyUser' custom header.

NUService: add method removeCustomHeader

---

elasticsearch/ESTabify.js

@natabal Please review for ES based Search on nested columns, must work for most of the cases.

[feature]: proceess nested query response

---

elasticsearch/ESService.js
tabify/nsgDiskUsage.js
tabify/top20TalkerAARDomain.js

@nxanil I need this change for a new feature! please review to make sure I do not break existing functionality! Thanks!

Add support for custom tabification on ES query responses.

---

VSDService.js
elasticsearch/ESRESTConnection.js
elasticsearch/ESService.js

@natabal 
Add methods to check ES and VSD connection status. Please have a look.

[feature]: add ES connection check

---

NUAttribute.js

- tested both positive and negative scenarios

fix list attribute validation

---

elasticsearch/ESService.js

@natabal 
Fix tabify issue https://github.com/nuagenetworks/vis-graphs/issues/128.
Please have a look.

Fix tabify issue #128

---

NUService.js

- light GET API used bu default
- can be disabled by passing prop light = false

fetchAll - disable light GET

---

VSDService.js

@natabal 
Fix issue coming due to PR #107. Please review and merge it ASAP.

[Bug] fix vsd service issue

---

elasticsearch/ESRESTConnection.js
elasticsearch/ESService.js

@natabal Please review.
Ref:- https://github.com/nuagenetworks/vsd-react-ui/pull/3046

Advance filter - ES

---

NUTemplateParser/index.js

@natabal Please review.
Ref:- nuagenetworks/vsd-react-ui#3046

Add searchText into requestId

---

elasticsearch/ESRESTConnection.js

@natabal @killanch 
Fix issue https://github.com/nuagenetworks/vsd-react-ui/issues/3241, https://github.com/nuagenetworks/vsd-react-ui/issues/3240. Please have a look.
Ref PR:- https://github.com/nuagenetworks/vsd-react-ui/pull/3245

[Bug]: Fix advanceSearch nested issue

---

tabify/hitsTabify.js
tabify/index.js

[r5.4] PROD-10737: tabify to make use of total hits (#129)

---

elasticsearch/ESRESTConnection.js
elasticsearch/ESService.js
elasticsearch/ESTabify.js

@natabal @killanch
Fix issue #126. Please have a look.
Ref PR:- https://github.com/nuagenetworks/vis-graphs/pull/251, https://github.com/nuagenetworks/vsd-react-ui/pull/3306

[Bug]: add support for count

---

tabify/nsgDiskUsage.js

vis-config changes: https://github.com/nuagenetworks/vis-config/pull/138
Sample:

Update nsgDiskUsage tabify to make use of ProgressBarGraph

---

elasticsearch/ESRESTConnection.js
elasticsearch/ESService.js

Circular dependencies:
1) elasticsearch/ESRESTConnection.js > elasticsearch/ESService.js

Fix circular dependencies

---

NUEntity.js

- tested with NSG module, filtering works as expected
- no api-specs impact

PROD-10910 - allow filtering by entity ID

---

tabify/gatewayRanksTabify.js
tabify/index.js

vis-config PR: https://github.com/nuagenetworks/vis-config/pull/151

VSD-38977: gateway selection tabify - add data for missing ranks and order by rank

---

tabify/gatewayRanksTabify.js
tabify/index.js

[r6.0] Gateway ranks tabify

---

tabify/index.js
tabify/webDomainNamesTabify.js

web domain names tabify - merge aggregations

---

NUTemplateParser/NUParser.js

@natabal 
Issue: https://github.com/nuagenetworks/vsd-react-ui/issues/3485 
Please have a look at the changes.
Also, I am left with testing from my end as well.
Note: You have to replace `term` with `terms` in queries, and values should be passed as array.

[Feature]: Add filterOptions to support a collection

---

elasticsearch/ESRESTConnection.js

@natabal @killanch 
I have making some changes to fix the [issue](https://github.com/nuagenetworks/js-bambou/issues/143), hopefully this will work. Please test at your end and let me know.

[Bug]: Fix es ping timeout issue

---

tabify/gatewayRanksTabify.js

* ubr gw selection - tabify changes
* update tabify to ensure rank 0 at the last
* replace var with const

VSD-39001 UBR gw selection - tabify changes (#148)

---

elasticsearch/ESRESTConnection.js
elasticsearch/ESService.js

@natabal @killanch
Fix issue https://github.com/nuagenetworks/vsd-react-ui/issues/3469. Please have a look.
Ref PR:- https://github.com/nuagenetworks/vsd-react-ui/issues/3497

[Bug]: Fix duplicate mapping issue

---

tabify/gatewayRanksTabify.js

fix gateway ranks tabify

---

tabify/nsgDiskUsage.js

@natabal 
Fix ProgressBar Graph NaN issue
Ref: https://github.com/nuagenetworks/vis-graphs/pull/378

[Fix]: ProgressBar Graph NaN issue

---

tabify/tiTopRiskyPublicIPsSecCatsTabify.js

Screenshots:
- Enterprise level
- Before
- After
- Domain level
- Before
- After

Sort Top Risky Public IPs by desc cardinality

---

tabify/fecHeatmapTabify.js

VSD-50878 FEC: Heatmap with wider color scales

---

tabify/fecHeatmapTabify.js

VSD-50878 FEC: Heatmap with wider color scales (#180)

---

elasticsearch/ESTabify.js

- added support for using "method" to transform object in query response
- sample usage in https://github.com/nuagenetworks/vis-config/pull/204, https://github.com/nuagenetworks/vis-config/pull/204/files#diff-2a1d7ce5de164b66c209d8413d6229289d71eb69e24e36ad8064a092a2cc2dc5R67

VSD-47571 - use custom method to transform object in query response

---

tabify/fecHeatmapTabify.js

VSD-51867 Heatmap color changed for >10% loss and when there is no loss (#186)

---

tabify/fecHeatmapTabify.js
tabify/utils.js

cherry-pick of #189 
* VSD-51867 Fixing No Data in Heatmap
* Refactor
* Code review comments

VSD-51867 Fixing No Data in Heatmap (#189)

---

elasticsearch/ESRESTConnection.js

- cherry-pick of r20.10 commit

fix VSD-51064 - increase ES connection timeout to 120sec (#188)

---

elasticsearch/ESRESTConnection.js

Co-authored-by: Karthigeyan Illancheran <karthigeyan.illancheran@nokia.com>

VSD-51763 include column type from mapping response (#192)

---

NURESTConnection.js

Related to https://github.com/nuagenetworks/vsd-react-ui/pull/4958

PROD-11873 VSD Maintenance mode support - Handle 503 - Service unavailable err -r20.10

---

NURESTConnection.js

Cherry picked https://github.com/nuagenetworks/js-bambou/pull/195
Related to https://github.com/nuagenetworks/vsd-react-ui/pull/4959

PROD-11873 VSD Maintenance mode support - Handle 503 - Service unavailable err

---

NURESTConnection.js
NUService.js

cherry pick of https://github.com/nuagenetworks/js-bambou/pull/198

Bulk delete funtionality

---

NUService.js

cherry pick of https://github.com/nuagenetworks/js-bambou/pull/201/files

VSD-56967 - User is unable to access UI after entering incorrect password on the User preferences page-0.0
